export const footerData = [
    {
        id:1,
        name:'Nigeria',
        img:'https://st.depositphotos.com/3519321/5096/i/450/depositphotos_50964593-stock-photo-nigerias-national-flag.jpg',
        isActive:true
    },
    {
        id:2,
        name:'Cameroon',
        img:'https://s3.amazonaws.com/images.wpr.com/flag-pages/png1000/cm.png',
        isActive:false
    },
    {
        id:3,
        name:'Ivory Coast',
        img:'https://cdn.britannica.com/48/5048-004-EA370A21/Flag-Cote-dIvoire.jpg',
        isActive:false
    },
    {
        id:4,
        name:'Rwanda',
        img:'https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Rwanda.svg',
        isActive:false
    },
    {
        id:5,
        name:'Tanzania',
        img:'https://cdn.britannica.com/20/20-004-EB20A026/Flag-Tanzania.jpg',
        isActive:false
    },
    {
        id:6,
        name:'United States',
        img:'https://cdn.britannica.com/79/4479-050-6EF87027/flag-Stars-and-Stripes-May-1-1795.jpg',
        isActive:false
    },
    {
        id:7,
        name:'Egypt',
        img:'https://cdn.britannica.com/85/185-004-1EA59040/Flag-Egypt.jpg',
        isActive:false
    },
    {
        id:8,
        name:'Kenya',
        img:'https://cdn.britannica.com/15/15-004-B5D6BF80/Flag-Kenya.jpg',
        isActive:false
    },
    {
        id:9,
        name:'Senegal',
        img:'https://cdn.britannica.com/70/5070-004-2963C5E1/Flag-Senegal.jpg',
        isActive:false
    },
    {
        id:10,
        name:'Uganda',
        img:'https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg',
        isActive:false
    },
    {
        id:11,
        name:'Zambia',
        img:'https://cdn.britannica.com/31/4231-004-F1DBFAE7/Flag-Zambia.jpg',
        isActive:false
    },
    {
        id:12,
        name:'Ghana',
        img:'https://cdn.britannica.com/54/5054-004-A09ABCDF/Flag-Ghana.jpg',
        isActive:false
    },
    {
        id:13,
        name:'Malawi',
        img:'https://cdn.britannica.com/21/4221-004-93C8B4EC/Flag-Malawi.jpg',
        isActive:false
    },
]